version: '3'
services:
  wordpress:
    image: php:7.3.6-fpm-alpine3.9
    volumes:
      - ./:/var/www/html
    restart: always
    depends_on: 
      - mysql

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}

  nginx:
    build: ./nginx
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    depends_on:
      - wordpress